services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8081:80"

  laravel:
    build: .
    container_name: laravel_app
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: app123
    command: >
      sh -c "
      set -e;
      if [ ! -f vendor/autoload.php ]; then
        echo 'Instalando dependencias de Composer...';
        composer install --no-interaction --prefer-dist --optimize-autoloader;
      fi;
      php artisan serve --host=0.0.0.0 --port=8000
      "


volumes:
  mysql_data:
